apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wayback-search
  description: Search of the wayback machine
#   annotations:
#     backstage.io/techdocs-ref: value
spec:
  type: service
  lifecycle: production
  owner: team-a
  providesApis:
    - wayback-search
  consumesApis:
    - wayback-archive
    
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example
  description: example.com
  annotations:
    backstage.io/techdocs-ref: value
spec:
  type: website
  lifecycle: production
  owner: user:guest
